config/routes.rb
Rails.application.routes.draw do

  get 'types/index'

  get 'types/show'

  get 'types/new'

  get 'types/create'

  get 'types/edit'

  get 'types/update'

  get 'types/destroy'

  get 'home_banners/index'

  get 'home_banners/show'

  get 'home_banners/new'

  get 'home_banners/create'

  get 'home_banners/edit'

  get 'home_banners/update'

  get 'home_banners/destroy'

  get 'shop_banners/index'

  get 'shop_banners/show'

  get 'shop_banners/new'

  get 'shop_banners/create'

  get 'shop_banners/edit'

  get 'shop_banners/update'

  get 'shop_banners/destroy'

  get 'banners/index'

  get 'banners/show'

  get 'banners/new'

  get 'banners/create'

  get 'banners/edit'

  get 'banners/update'

  get 'banners/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/create'

  get 'users/new'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'purchases/index'

  get 'purchases/show'

  get 'purchases/new'

  get 'purchases/create'

  get 'purchases/edit'

  get 'purchases/update'

  get 'purchases/destroy'

  get 'complements/index'

  get 'complements/show'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/new'

  get 'complements/create'

  get 'complements/destroy'

  get 'raw_subcategories/index'

  get 'raw_subcategories/show'

  get 'raw_subcategories/new'

  get 'raw_subcategories/create'

  get 'raw_subcategories/edit'

  get 'raw_subcategories/update'

  get 'raw_subcategories/destroy'

  get 'raw_categories/index'

  get 'raw_categories/show'

  get 'raw_categories/new'

  get 'raw_categories/create'

  get 'raw_categories/edit'

  get 'raw_categories/update'

  get 'raw_categories/destroy'

  get 'raws/index'

  get 'raws/show'

  get 'raws/edit'

  get 'raws/update'

  get 'raws/new'

  get 'raws/create'

  get 'raws/destroy'

  get 'coupons/coupon_batch_actions' => "coupons#coupon_batch_actions", :as => 'coupon_batch_actions'

  get 'coupons/index'

  get 'coupons/show'

  get 'coupons/new'

  get 'coupons/create'

  get 'coupons/edit'

  get 'coupons/update'

  get 'coupons/destroy'

  get 'pictures/edit'

  get 'pictures/destroy'

  get 'colors/index'

  get 'colors/show'

  get 'colors/new'

  get 'colors/create'

  get 'colors/edit'

  get 'colors/update'

  get 'colors/destroy'

  get 'single_articles/index'

  get 'single_articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'categories/new'

  get 'categories/edit'

  get 'materials/index'

  get 'materials/show'

  get 'materials/new'

  get 'materials/edit'

  get 'articles/index'

  get 'articles/show'

  get 'articles/show_pics' => "articles#show_pics", :as => 'articles_gallery'

  get 'articles/new'

  get 'articles/create'

  get 'articles/edit'

  get 'articles/update'

  get 'articles/destroy'

  get 'articles/batch_actions' => "articles#batch_actions", :as => 'batch_actions'

  get 'articles/set_picture' => "articles#set_picture", :as => 'set_picture'

  get 'articles/import_view' => "articles#import_view", :as => 'import_view'

  get 'articles/edit_multiple' => "articles#edit_multiple", :as => 'edit_multiple'

  get 'articles/update_multiple' => "articles#update_multiple", :as => 'update_multiple'

  get 'articles/raw_index' => "articles#raw_index", :as => 'raw_index'

  get 'articles/raw_new' => "articles#raw_new", :as => 'raw_new'

  get 'articles/raw_show' => "articles#raw_show", :as => 'raw_show'

  get 'articles/set_auction' => "articles#set_auction", :as => 'set_auction'

  get 'articles/create_auction' => "articles#create_auction", :as => 'create_auction'

  get 'articles/index_auction' => "articles#index_auction", :as => 'index_auction'

  get 'complements/complement_set_picture' => "complements#complement_set_picture", :as => 'complement_set_picture'

  get 'dashboards/batch_options' => "dashboards#batch_options", :as => 'batch_options'

  root :to => 'dashboards#index'

  devise_for :admin_users, controllers: {sessions: "admin_users/sessions", registrations: "admin_users/registrations"}

  devise_scope :admin_user do
    get "login", to: "devise/sessions#new"
    authenticated :admin_user do
      root :to => 'dashboards#index', as: :authenticated_root
      get "sign_up", to: "devise/registrations#new"
    end
    unauthenticated :admin_user do
      root :to => 'admin_users/sessions#new', as: :unauthenticated_root
    end

    get "admin_users/sign_out" => redirect("devise/sessions#new")

    resources :home_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :shop_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :purchases
    resources :complements do
      put :complement_set_picture, on: :collection
    end
    resources :dashboards do
      put :batch_options, on: :collection
    end
    resources :categories
    resources :articles do
      get :index_auction, on: :collection
      put :create_auction, on: :collection
      put :set_auction, on: :collection
      get :raw_edit, on: :collection
      get :raw_new, on: :collection
      put :raw_show, on: :collection
      get :raw_index, on: :collection
      put :batch_actions, on: :collection
      put :set_discount, on: :collection
      put :set_picture, on: :collection
      post :import, on: :collection
      put :edit_multiple, on: :collection
      post :update_multiple, on: :collection
    end
    resources :materials
    resources :single_articles
    resources :colors
    resources :types
    resources :pictures
    resources :raw_categories
    resources :raw_subcategories
    resources :coupons do
      put :coupon_batch_actions, on: :collection
    end

  end

end

app/models/article.rb
# encoding: utf-8
class Article < ActiveRecord::Base
  require 'open-uri'
  require 'csv'

  belongs_to :color
  belongs_to :type

  has_many :related_articles
  has_many :related_articles, :through => :related_articles

  has_many :article_categories
  has_many :categories, :through => :article_categories

  has_many :carts_articles
  has_many :shopping_carts, :through => :carts_articles

  has_many :past_purchases
  has_many :users, :through => :past_purchases

  has_many :auctions

  belongs_to :material
  belongs_to :subcategory
  belongs_to :ssubcategory

  belongs_to :picture

  has_many :coupons

  has_many :single_articles
  accepts_nested_attributes_for :single_articles, allow_destroy: true

  has_many :pictures, :dependent => :destroy

  attr_accessor :colors

  def discount_job
    @art = Article.where("discount > 0")

    if !@art.empty?

      @art.each do |art|
        if art.start_date != nil && art.end_date != nil
          if art.start_date > DateTime.now && art.end_date < DateTime.now
            @art.update_all(on_discount: true)
          elsif art.end_date > DateTime.now
            @art.update_all(on_discount: false)
          end

      end

      end
    end
  end

  after_save { |article|

    article.single_articles.each do |sa|

      sa.title = article.title
      sa.code = article.code

      if sa.size != nil && sa.size != ""
        sa.title += "/"+sa.size.to_s
        sa.code += "-"+sa.size.to_s
      end


      if sa.amount == nil
        sa.amount = article.amount
      end

      if sa.warning == nil
        sa.warning = article.warning
      end

      sa.save
    end

  }

  filterrific(
      default_filter_params: { sorted_by: 'created_at_desc' },
      available_filters: [
          :sorted_by,
          :search_query,
          :with_material_id,
          :with_category_id,
          :with_created_at_gte
      ]
  )


  def self.import(file) #import csv-a u bazu

=begin
articles = CSV.new(open(file), {:headers => :first_row, :col_sep => ";" })

articles.each do |art|
  Article.create(art.to_hash)
end
=end
puts "usao je u import"
# runs through a loop in our CSV data
    CSV.new(open(file, "r:ISO-8859-2"), {:headers => true, :col_sep => ";"}).each do |row|
        # creates a user for each row in the CSV file
        puts"ovo je row: #{row}"
        puts "ovo je row.to_hash: #{row.to_hash}"
        Article.create(row.to_hash)
        puts "izradio je artikl"
      end

  end

  # define ActiveRecord scopes for
  # :search_query, :sorted_by, :with_country_id, and :with_created_at_gte

  scope :sorted_by, lambda { |sort_option|
                    # extract the sort direction from the param value.
                    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
                    case sort_option.to_s
                      when /^created_at_/

                        order("articles.created_at #{ direction }")
                      when /^updated_at_/

                        order("articles.updated_at #{ direction }")
                      when /^title_/

                        order("LOWER(articles.title) #{ direction }")
                      else
                        raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
                    end
                  }

  scope :with_category_id, lambda { |category_ids|
                          #where(category_id: [*category_ids])

                          # get a reference to the join table
                          art_cat = ArticleCategory.arel_table
                          # get a reference to the filtered table
                          articles = Article.arel_table
                          # let AREL generate a complex SQL query
                          where(
                                ArticleCategory \
                              .where(art_cat[:article_id].eq(articles[:id])) \
                              .where(art_cat[:category_id].in([*category_ids].map(&:to_i))) \
                              .exists
                            )
                          }


  scope :with_material_id, lambda { |material_ids|
                           where(material_id: [*material_ids])
                         }

  scope :with_created_at_gte, lambda { |ref_date|
                              where(created_at: [*ref_date])
                            }

  scope :search_query, lambda { |query|

                       return nil  if query.blank?

                       terms = query.downcase

                       # replace "*" with "%" for wildcard searches,
                       # append '%', remove duplicate '%'s

                       # configure number of OR conditions for provision
                       # of interpolation arguments. Adjust this if you
                       # change the number of OR conditions.
                       num_or_conds = 1
                       where(
                             "(LOWER(articles.title) LIKE ? OR LOWER(articles.title_eng) LIKE ?)", "%#{terms}%", "%#{terms}%"
                       )
                     }

  def self.options_for_sorted_by
    [
        ['Nazivu (a-z)', 'title_asc'],
        ['Datumu kreiranja (najnoviji)', 'created_at_desc'],
        ['Datumu kreiranja (stariji)', 'created_at_asc'],
        ['Datumu izmjene (najnoviji)', 'updated_at_desc'],
        ['Datumu izmjene (stariji)', 'updated_at_asc']
    ]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles_gallery.erb
<div id="filterrific_results">


  <div style="margin-bottom: 20px">
  <%= page_entries_info articles %>
  </div>
  <div class="row" >



  <% articles.each do |art| %>

  <div class="col-xs-6 col-md-2 js--msr-gall">
    <div class="container-fluid gallery" >
  <strong><%= art.title %></strong>
    </div>
    <% if art.picture != nil %>
        <%= link_to image_tag(art.picture.image.url(:gallery)) ,article_path(art.id), method: :get , class: 'thumbnail' %>
    <% else %>
        <%= link_to image_tag('placeholder.png') ,article_path(art.id), method: :get, class: 'thumbnail' %>
    <% end %>
  </div>

  <% end %>
</div>
</div>

<%= paginate articles %>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit_multiple.erb
<h3>Uredi Artikle</h3>

<%= form_tag update_multiple_path, method: :post, multipart: true do %>
    <% $art.each do |article| %>

        <div class="page-header head-page" >
          <h1><%= article.title %></h1>
        </div>

        <%= simple_fields_for "articles"+article.id.to_s,  article, html: {class: 'form-horizontal'} do |f| %>

            <%= f.input :raw, :as => :hidden %>

            <%= f.input :title, label: "Naziv" %>

            <%= f.input :title_eng, label: "Naziv na Engleskom" %>

            <% if !f.object.raw? %>
                <%= f.input :material_id, label: "Materijal", :collection => Material.all %>
                <%= f.input :category_ids , label: "Kategorije" ,collection: Material.all, as: :grouped_select, group_method: :categories, :input_html => { multiple: true } %>

                <%= f.simple_fields_for :related_articles do |r| %>
                    <%= f.label "Srodni artikli" %>
                    <%= r.input :related_article_ids, required: false, label: false  ,collection: Article.where(raw: false), selected: RelatedArticle.where(article_id: f.object.id).pluck(:related_article_id), :input_html => {class: 'chosen-select', multiple: true} %>
                    <%= r.input :related_article_codes, required: false, label: false, collection: Article.where(raw:false).pluck(:code), input_html: {class: 'chosen-select', multiple: true} %>
                <% end %>
            <% else %>
                <%= f.input :subcategory_id, label: "Kategorija", :collection => Subcategory.all %>
                <%= f.input :ssubcategory_id , label: "Podkategorija" , :collection => Subcategory.all, as: :grouped_select, group_method: :ssubcategories %>

                <%= f.simple_fields_for :related_articles do |r| %>
                    <%= f.label "Srodni artikli" %>
                    <%= r.input :related_article_ids, required: false, label: false  ,collection: Article.where(raw: true), selected: RelatedArticle.where(article_id: f.object.id).pluck(:related_article_id), :input_html => {class: 'chosen-select', multiple: true} %>
                    <%= r.input :related_article_codes, required: false, label: false, collection: Article.where(raw:true).pluck(:code), input_html: {class: 'chosen-select', multiple: true} %>
                <% end %>
            <% end %>


            <%= f.label "Boja" %>
            <%= f.input :color_id, collection: Color.all , label: false %>

            <%= f.label "Tip" %>
            <%= f.input :type_id, collection: Type.all , label: false %>

            <div class="control-group">
              <%= f.label :pictures, label: "Slike", :class => 'control-label' %>
              <div class="controls">


                <%= file_field_tag "images"+f.object.id.to_s+"[]", type: :file, multiple: true %>
                <br/>
                <% article.pictures.each do |p| %>
                    <div style="margin-top: 15px;">
                      <%= link_to "Postavi kao Avatar", set_picture_path(p.id), class: "btn btn-default"%>
                      <%= link_to 'Delete',  picture_path(p.id),  method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-default" %>
                      <%= image_tag p.image.url(:thumb) %>
                    </div>
                <% end %>

                <p></p>
              </div>
            </div>

            <div style="margin-top: 20px; margin-bottom: 20px;">
              <%= f.simple_fields_for :single_articles do |single_article| %>
            <%= render 'single_article_fields', :f => single_article  %>
        <% end %>

        <div class="links">
          <%= link_to_add_association 'Dodaj Veličinu', f, :single_articles, class: "btn btn-info" %>
        </div>
        </div>


            <%= f.input :short_description, label: "Kratki opis", maxlength: 17, placeholder: "Maksimalno 17 znakova" %>

            <%= f.input :short_description_eng, label: "Kratki opis na Engleskom", maxlength: 17, placeholder: "Maksimalno 17 znakova" %>

            <%= f.input :description, label: "Opis" %>

            <%= f.input :description_eng, label: "Opis na Engleskom" %>

            <%= f.input :weight, label: "Težina" %>

            <%= f.input :dimension, label: "Dimenzije" %>

            <%= f.input :code, label: "Kod" %>

            <%= f.input :suppliers_code, label: "Kod Dobavljača" %>

            <%= f.input :amount, label: "Količina" %>

            <%= f.input :warning, label: "Limit za upozorenje" %>

            <%= f.input :cost, label: "Cijena" %>

            <%= f.input :discount, label: "Popust" %>

            <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
              <span class="input-group-addon">
                 <%= f.check_box :for_sale, label: "Postavi na prodaju", type: "checkbox" %>
              </span>
              <%= f.label "Postavi na prodaju", type: "text", class: "form-control" %>
            </div>

                  <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
            <span class="input-group-addon">
               <%= f.check_box :feature_product, label: "Postavi na prodaju", type: "checkbox" %>
            </span>
                    <%= f.label "Postavi kao izdvojeni artikl", type: "text", class: "form-control" %>
                  </div>

            <div style="height: 50px;">        <div class="page-header head-page" >
              <h1></h1>
            </div></div>

        <% end %>

    <% end %>
        <%= submit_tag "Izmijeni artikle", class: "btn btn-success" %>
        <%= link_to "Cancel", articles_path, class: "btn btn-default", method: :get %>
<% end %>

app/views/articles/index.html.erb
<div class="btn-group">
  <%= link_to "Novi Artikl", articles_new_path, class: "btn btn-success" %>
  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Uvezi CSV", import_view_path %></li>

  </ul>
</div>

<%= link_to "Grafički pogled", articles_gallery_path, class: "btn btn-default pull-right RbtnMargin" %> <%= link_to "Aukcije", index_auction_path, class: "btn btn-default pull-right RbtnMargin" %> <%= link_to "Kompleti", complements_path, class: "btn btn-default pull-right" %>
<div class="page-header head-page">
  <h1>Nakit</h1>
</div>


<%= form_tag batch_actions_path, :method => :put do |f| %>

 <div style="margin-bottom: 5px;" >

    <div class="dropdown" >
      <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="width: 105px;">
        Opcije
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">

        <li><a><%= submit_tag "Postavi popust", style: "background: white;" %></a></li>
        <li><a><%= submit_tag "Makni sa popusta", style: "background: white;" %></a></li>
        <li role="separator" class="divider"></li>
        <li><a><%= submit_tag "Stavi na Aukciju", style: "background: white;" %></a></li>
        <li role="separator" class="divider"></li>
        <li><a><%= submit_tag "Uredi odabrane artikle", style: "background: white;"  %></a></li>
        <li role="separator" class="divider"></li>
        <li><a><%= submit_tag "Stavi na prodaju", style: "background: white;"  %></a></li>
        <li><a><%= submit_tag "Makni sa prodaje", style: "background: white;"  %></a></li>
        <li role="separator" class="divider"></li>
        <li><a><%= submit_tag "Stavi u Izdvojene artikle", style: "background: white;"  %></a></li>
        <li><a><%= submit_tag "Makni iz Izdvojenih artikla", style: "background: white;"  %></a></li>

      </ul>

      <%= submit_tag "Izbriši artikle",data: { confirm: 'Jeste li sigurni da želite obrisati odabrane artikle?' }, class: "btn btn-danger"%>
    </div>

 </div>

    <%= render partial: 'articles/articles_grid' %>

<% end %>

app/views/articles/show.html.erb
<%= javascript_tag do %>
    $(function(){

    ts = new Date(gon.date);

    if((new Date()) > ts){
    // The new year is here! Count towards something else.
    // Notice the *1000 at the end - time must be in milliseconds
    ts = new Date(gon.date);
    }

    $('#countdown').countdown({
    timestamp	: ts,
    callback	: function(days, hours, minutes, seconds){

    }
    });

    });
<% end %>

<%= link_to "Uredi Artikl", articles_edit_path(@article.id), class: "btn btn-primary" %> <%= link_to 'Delete',  @article,  method: :delete, data: { confirm: 'Jeste li sigurni?' },class: "btn btn-danger" %> <% if @article.raw? %> <%= link_to "Svi Repromaterijali", raw_index_articles_path, class: "btn btn-default pull-right" %> <% else %> <%= link_to "Svi Artikli", articles_path, class: "btn btn-default pull-right" %> <% end %>
<div class="page-header head-page">
  <h1><%= @article.title %><% if !@article.title_eng.blank? %> <small><%= @article.title_eng %></small><% end %></h1>
</div>

<% if !@article.for_sale? %>
  <div class="alert alert-danger" role="alert">
    <h4 style="margin-bottom: 0px;">Artikl nije stavljen na prodaju!</h4>
  </div>
<% end %>

<% if @article.raw? %>
    <div class="alert alert-warning" role="alert">
      <h4 style="margin-bottom: 0px;">Repromaterijal</h4>
    </div>
<% end %>

<!--<div id="clock"></div>-->

<% if @article.discount != nil && @article.end_date != nil && @article.end_date > DateTime.now && @article.start_date <= DateTime.now %>
  <div id="countdown" class="countdownHolder" style="width: 100%; text-align: left">
    <span class="countDays">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

    <span class="countDiv countDiv0"></span>

    <span class="countHours">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

    <span class="countDiv countDiv1"></span>

    <span class="countMinutes">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

    <span class="countDiv countDiv2"></span>

    <span class="countSeconds">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

  </div>
<% end %>

  <% if !@article.picture.nil? %>
    <%= image_tag(@article.picture.image.url(:gallery)) %>
  <% else %>
    <%= image_tag('placeholder.png') %>
  <% end %>
<br/>
<div class="panel panel-info" style="margin-top: 10px">
  <div class="panel-heading">
    <h3 class="panel-title">Info</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-6 col-md-2">
        <strong>Boja:</strong><p><%= @article.color != nil ? @article.color.title : "Nema boju!" %></p>
      </div>
       <div class="col-xs-6 col-md-2">
        <strong>Tip:</strong><p><%= @article.type != nil ? @article.type.title : "Nema tip!" %></p>
      </div>
    </div>
    <div class="row" >
      <% if !@article.raw? %>
        <div class="col-xs-6 col-md-2" >
        <strong>Materijal:</strong>  <% if @article.material != nil %> <p><%= link_to @article.material.title, material_path(@article.material.id) %> <% else %> Nije postavljen materijal <% end %></p>
        </div>

        <div class="col-xs-6 col-md-2" >
        <strong>Kategorije:</strong> <% if @article.categories != nil %> <% @article.categories.each do |cat| %>
              <p><%= link_to cat.title, category_path(cat.id) %></p>
              <% end %>
                <p><% else %> Nije postavljena kategorija <% end %></p>
        </div>
      <% else %>
          <div class="col-xs-6 col-md-2" >
            <strong>Kategorija:</strong>  <% if @article.subcategory != nil %> <p><%= link_to @article.subcategory.title, raw_categories_show_path(@article.subcategory.id) %> <% else %> Nije postavljen materijal <% end %></p>
          </div>

          <div class="col-xs-6 col-md-2" >
            <strong>Podkategorija:</strong> <% if @article.ssubcategory != nil %> <p><%= link_to @article.ssubcategory.title, raw_subcategories_show_path(@article.ssubcategory.id) %> <% else %> Nije postavljena kategorija <% end %></p>
          </div>
      <% end %>
    <div class="col-xs-6 col-md-2" >
    <strong>Kod:</strong> <p><%= @article.code %></p>
    </div>


    <div class="col-xs-6 col-md-2" >
    <strong>Cijena<% if @discount_prize %>(prije popusta) <% end %>:</strong> <p><%= number_to_currency(@article.cost, :unit => 'Kn', :format => "%n %u") %></p>
    </div>

    <div class="col-xs-6 col-md-2">
      <strong>Dimenzije:</strong><p><%= @article.dimension %></p>
    </div>

      </div>
<br/>
    <div class="row">
      <div class="col-xs-6 col-md-2" >
        <strong>Količina:</strong> <p><%= @article.amount %></p>
      </div>

      <div class="col-xs-6 col-md-2" >
        <strong>Upozorenje(količina):</strong> <p><%= @article.warning %></p>
      </div>

      <div class="col-xs-6 col-md-2" >
        <strong>Kod Dobavljača:</strong> <p><%= @article.suppliers_code %></p>
      </div>

      <% if @discount_prize != nil%>
          <div class="col-xs-6 col-md-2" >
            <strong>Cijena(poslije popusta):</strong> <p><%= number_to_currency(@discount_prize, :unit => 'Kn', :format => "%n %u") %></p>
          </div>

          <div class="col-xs-6 col-md-2" >
            <strong>Popust:</strong> <p><%= @article.discount.to_s+"%" %></p>
          </div>

          <% if @article.start_date != nil %>
          <div class="col-xs-6 col-md-2" >
            <strong>Pocetak-Kraj popusta:</strong> <p><%= @article.start_date.strftime("%d.%m.%Y. %H:%M").to_s+" - "+@article.end_date.strftime("%d.%m.%Y. %H:%M") %></p>
          </div>
          <% end %>
      <% end %>
    </div>



  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Srodni Artikli</h3>
  </div>
  <ul class="list-group">
    <% if !@rel_arts.nil? %>
        <% @rel_arts.each do |art| %>
            <%= link_to art.title, article_path(art.id), class:'list-group-item', method: :get %>
        <% end %>
    <% end %>
  </ul>
</div>

<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Opis</h3>
  </div>
  <div class="panel-body">
    <div class="page-header head-page">
      <h5>HRV:</h5>
    </div>
    <% if !@article.description.blank? %>
      <%= @article.description %>
    <% else %>
      Nema opisa!
    <% end %>

    <div class="page-header">
      <h5>ENG:</h5>
    </div>
    <% if !@article.description_eng.blank? %>
        <%= @article.description_eng %>
    <% else %>
        No description!
    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Kuponi</h3>
  </div>

  <ul class="list-group">
    <% @article.coupons.each do |c| %>
<%= link_to c.discount.to_s+"%"+"- - -"+(c.used  ? "Iskorišten" : "Nije Iskorišten"), coupon_path(c.id), class: "list-group-item" %>
    <% end %>
  </ul>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Pojedinačni Artikli</h3>
  </div>
  <ul class="list-group">
    <% @article.single_articles.each do |art| %>
        <%= link_to art.title, single_article_path(art.id), class:"list-group-item" %>
    <% end %>
  </ul>

</div>



<p><strong>Slike:</strong></p>

<div class="row" >

<%= render_gallery_for @article.pictures, list_tag: :div, item_tag: :p, item_class: "col-xs-6 col-md-3"  %>

</div>

<% @article.single_articles.each do |sa| %>
    <div class="row" >
        <% if sa.pictures.first != nil %>
          <p><strong><%= sa.title %></strong></p>
          <%= render_gallery_for sa.pictures, list_tag: :div, item_tag: :p, item_class: "col-xs-6 col-md-3"  %>
        <% end %>
    </div>
<% end %>