config/routes.rb
Rails.application.routes.draw do

  get 'types/index'

  get 'types/show'

  get 'types/new'

  get 'types/create'

  get 'types/edit'

  get 'types/update'

  get 'types/destroy'

  get 'home_banners/index'

  get 'home_banners/show'

  get 'home_banners/new'

  get 'home_banners/create'

  get 'home_banners/edit'

  get 'home_banners/update'

  get 'home_banners/destroy'

  get 'shop_banners/index'

  get 'shop_banners/show'

  get 'shop_banners/new'

  get 'shop_banners/create'

  get 'shop_banners/edit'

  get 'shop_banners/update'

  get 'shop_banners/destroy'

  get 'banners/index'

  get 'banners/show'

  get 'banners/new'

  get 'banners/create'

  get 'banners/edit'

  get 'banners/update'

  get 'banners/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/create'

  get 'users/new'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'purchases/index'

  get 'purchases/show'

  get 'purchases/new'

  get 'purchases/create'

  get 'purchases/edit'

  get 'purchases/update'

  get 'purchases/destroy'

  get 'complements/index'

  get 'complements/show'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/new'

  get 'complements/create'

  get 'complements/destroy'

  get 'raw_subcategories/index'

  get 'raw_subcategories/show'

  get 'raw_subcategories/new'

  get 'raw_subcategories/create'

  get 'raw_subcategories/edit'

  get 'raw_subcategories/update'

  get 'raw_subcategories/destroy'

  get 'raw_categories/index'

  get 'raw_categories/show'

  get 'raw_categories/new'

  get 'raw_categories/create'

  get 'raw_categories/edit'

  get 'raw_categories/update'

  get 'raw_categories/destroy'

  get 'raws/index'

  get 'raws/show'

  get 'raws/edit'

  get 'raws/update'

  get 'raws/new'

  get 'raws/create'

  get 'raws/destroy'

  get 'coupons/coupon_batch_actions' => "coupons#coupon_batch_actions", :as => 'coupon_batch_actions'

  get 'coupons/index'

  get 'coupons/show'

  get 'coupons/new'

  get 'coupons/create'

  get 'coupons/edit'

  get 'coupons/update'

  get 'coupons/destroy'

  get 'pictures/edit'

  get 'pictures/destroy'

  get 'colors/index'

  get 'colors/show'

  get 'colors/new'

  get 'colors/create'

  get 'colors/edit'

  get 'colors/update'

  get 'colors/destroy'

  get 'single_articles/index'

  get 'single_articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'categories/new'

  get 'categories/edit'

  get 'materials/index'

  get 'materials/show'

  get 'materials/new'

  get 'materials/edit'

  get 'articles/index'

  get 'articles/show'

  get 'articles/show_pics' => "articles#show_pics", :as => 'articles_gallery'

  get 'articles/new'

  get 'articles/create'

  get 'articles/edit'

  get 'articles/update'

  get 'articles/destroy'

  get 'articles/batch_actions' => "articles#batch_actions", :as => 'batch_actions'

  get 'articles/set_picture' => "articles#set_picture", :as => 'set_picture'

  get 'articles/import_view' => "articles#import_view", :as => 'import_view'

  get 'articles/edit_multiple' => "articles#edit_multiple", :as => 'edit_multiple'

  get 'articles/update_multiple' => "articles#update_multiple", :as => 'update_multiple'

  get 'articles/raw_index' => "articles#raw_index", :as => 'raw_index'

  get 'articles/raw_new' => "articles#raw_new", :as => 'raw_new'

  get 'articles/raw_show' => "articles#raw_show", :as => 'raw_show'

  get 'articles/set_auction' => "articles#set_auction", :as => 'set_auction'

  get 'articles/create_auction' => "articles#create_auction", :as => 'create_auction'

  get 'articles/index_auction' => "articles#index_auction", :as => 'index_auction'

  get 'complements/complement_set_picture' => "complements#complement_set_picture", :as => 'complement_set_picture'

  get 'dashboards/batch_options' => "dashboards#batch_options", :as => 'batch_options'

  root :to => 'dashboards#index'

  devise_for :admin_users, controllers: {sessions: "admin_users/sessions", registrations: "admin_users/registrations"}

  devise_scope :admin_user do
    get "login", to: "devise/sessions#new"
    authenticated :admin_user do
      root :to => 'dashboards#index', as: :authenticated_root
      get "sign_up", to: "devise/registrations#new"
    end
    unauthenticated :admin_user do
      root :to => 'admin_users/sessions#new', as: :unauthenticated_root
    end

    get "admin_users/sign_out" => redirect("devise/sessions#new")

    resources :home_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :shop_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :purchases
    resources :complements do
      put :complement_set_picture, on: :collection
    end
    resources :dashboards do
      put :batch_options, on: :collection
    end
    resources :categories
    resources :articles do
      get :index_auction, on: :collection
      put :create_auction, on: :collection
      put :set_auction, on: :collection
      get :raw_edit, on: :collection
      get :raw_new, on: :collection
      put :raw_show, on: :collection
      get :raw_index, on: :collection
      put :batch_actions, on: :collection
      put :set_discount, on: :collection
      put :set_picture, on: :collection
      post :import, on: :collection
      put :edit_multiple, on: :collection
      post :update_multiple, on: :collection
    end
    resources :materials
    resources :single_articles
    resources :colors
    resources :types
    resources :pictures
    resources :raw_categories
    resources :raw_subcategories
    resources :coupons do
      put :coupon_batch_actions, on: :collection
    end

  end

end

app/controllers/raw_categories_controller.rb
class RawCategoriesController < ApplicationController
  before_filter :authenticate_admin_user!

  def index
    @page_title = "Kategorije"
    @subcategories = Subcategory.all
    @ssubcategories = Ssubcategory.all
  end

  def show
    @subcategory = Subcategory.find(params[:format])
    @page_title = "Kategorije | " + @subcategory.title
  end

  def new
    @subcategory = Subcategory.new
    @page_title = "Kategorije | New"
  end

  def create
    @subcategory = Subcategory.new(subcategory_params)

    @subcategory.save

    flash[:notice] = "Dodan je novi materijal!"

    redirect_to raw_categories_index_path
  end

  def edit
    @raw_category = Subcategory.find(params[:format])
    @page_title = "Edit | "+@raw_category.title
  end

  def update
    @subcategory = Subcategory.find(params[:id])

    @subcategory.update(subcategory_params)

    flash[:notice] = "Materijal je izmijenjen!"

    redirect_to raw_categories_index_path
  end

  def destroy
    @subcategory = Subcategory.find(params[:format])

    @subcategory.destroy

    flash[:notice] = "Kategorija za repromaterijal je izbrisana!"

    redirect_to raw_categories_index_path
  end

  protected
  def subcategory_params
    params.require(:subcategory).permit(:title,:title_eng, { ssubcategory_ids:[]}, :has_colors, :has_types)
  end
end

app/helpers/raw_categories_helper.rb
module RawCategoriesHelper
end

app/views/raw_categories/create.html.erb
<h1>RawCategories#create</h1>

app/views/raw_categories/destroy.html.erb
<h1>RawCategories#destroy</h1>
<p>Find me in app/views/raw_categories/destroy.html.erb</p>

app/views/raw_categories/edit.html.erb
<h3>Uredi Kategoriju za Repromaterijal</h3>

<%= simple_form_for @raw_category , url: raw_category_path(@raw_category.id),html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :title, label: "Naziv" %>

    <%= f.input :title_eng, label: "Naziv na Engleskom" %>

    <%= f.input :avatar, label: "Slika" , as: :file %>

    <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
      <span class="input-group-addon">
         <%= f.check_box :has_colors, label: false, type: "checkbox" %>
      </span>
      <%= f.label "Filter za boju?", type: "text", class: "form-control" %>
    </div>

    <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
      <span class="input-group-addon">
         <%= f.check_box :has_types, label: false, type: "checkbox" %>
      </span>
      <%= f.label "Filter za tip?", type: "text", class: "form-control" %>
    </div>

    <%= f.label "Podkategorija" %>
    <%= f.association :ssubcategories, label: false, collection: Ssubcategory.all, multiple: true, :include_blank => true, :input_html => {class: 'chosen-select'} %>

    <%= f.button :submit, "Izradi kategoriju", class: "btn btn-success" %>
    <%= link_to "Cancel", raw_categories_index_path, class: "btn btn-default" %>

<% end %>

app/views/raw_categories/index.html.erb
<%= link_to "Nova Kategorija", raw_categories_new_path, class: "btn btn-success" %> <%= link_to "Nova Podkategorija", raw_subcategories_new_path, class: "btn btn-info" %> <%= link_to "Repromaterijal", raw_index_path, class: "btn btn-default pull-right" %>
<div class="page-header head-page">
  <h1>Kategorije <small>Repromaterijal</small></h1>
</div>

<div class="list-group">
  <% @subcategories.each do |cat| %>
      <%= link_to cat.id.to_s+". "+cat.title, raw_categories_show_path(cat.id), class: 'list-group-item' %>
  <% end %>
</div>

<div class="page-header head-page">
</div>
<div class="page-header head-page">
  <h2>Potkategorije <small>Repromaterijal</small></h2>
</div>

<div class="list-group">
  <% @ssubcategories.each do |cat| %>
      <%= link_to cat.id.to_s+". "+cat.title, raw_subcategories_show_path(cat.id), class: 'list-group-item' %>
  <% end %>
</div>

app/views/raw_categories/new.html.erb
<h3>Nova Kategorija za Repromaterijal</h3>

<%= simple_form_for @subcategory, url: raw_categories_path ,html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :title, label: "Naziv" %>

    <%= f.input :title_eng, label: "Naziv na Engleskom" %>

    <%= f.input :avatar, label: "Slika" , as: :file %>

    <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
      <span class="input-group-addon">
         <%= f.check_box :has_colors, label: false, type: "checkbox" %>
      </span>
      <%= f.label "Filter za boju?", type: "text", class: "form-control" %>
    </div>

    <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
      <span class="input-group-addon">
         <%= f.check_box :has_types, label: false, type: "checkbox" %>
      </span>
      <%= f.label "Filter za tip?", type: "text", class: "form-control" %>
    </div>



    <%= f.label "Podkategorija" %>
    <%= f.association :ssubcategories, label: false, collection: Ssubcategory.all, multiple: true, :include_blank => true, :input_html => {class: 'chosen-select'} %>

    <%= f.button :submit, "Izradi kategoriju", class: "btn btn-success" %>
    <%= link_to "Cancel", raw_categories_index_path, class: "btn btn-default" %>

<% end %>

app/views/raw_categories/show.html.erb
<%= link_to "Uredi Kategoriju za Repromaterijal", raw_categories_edit_path(@subcategory.id), class: "btn btn-primary" %> <%= link_to 'Delete', raw_categories_destroy_path(@subcategory.id),  method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %> <%= link_to "Sve (Pod)Kategorije za Repromaterijal", raw_categories_path, class: "btn btn-default pull-right" %>
<div class="page-header head-page">
  <h1><%= @subcategory.title %><% if @subcategory.title_eng != nil %> <small><%= @subcategory.title_eng %></small><% end %></h1>
</div>

<div style="margin-bottom: 15px;" >
  <% if !@subcategory.avatar_file_name.nil? %>
      <%= image_tag(@subcategory.avatar.url(:thumb)) %>
  <% else %>
      <%= image_tag('placeholder.png') %>
  <% end %>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Podkaterije</h3>
  </div>
  <ul class="list-group">
    <% @subcategory.ssubcategories.each do |cat| %>
        <%= link_to cat.id.to_s+". "+cat.title, raw_subcategories_show_path(cat.id), class:"list-group-item" %>
    <% end %>
  </ul>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Artikli</h3>
  </div>
  <ul class="list-group">
    <% @subcategory.articles.each do |art| %>
        <%= link_to art.title, article_path(art.id), method: :get ,class:"list-group-item"  %>
    <% end %>
  </ul>
</div>

app/views/raw_categories/update.html.erb
<h1>RawCategories#update</h1>
<p>Find me in app/views/raw_categories/update.html.erb</p>