config/routes.rb
Rails.application.routes.draw do

  get 'types/index'

  get 'types/show'

  get 'types/new'

  get 'types/create'

  get 'types/edit'

  get 'types/update'

  get 'types/destroy'

  get 'home_banners/index'

  get 'home_banners/show'

  get 'home_banners/new'

  get 'home_banners/create'

  get 'home_banners/edit'

  get 'home_banners/update'

  get 'home_banners/destroy'

  get 'shop_banners/index'

  get 'shop_banners/show'

  get 'shop_banners/new'

  get 'shop_banners/create'

  get 'shop_banners/edit'

  get 'shop_banners/update'

  get 'shop_banners/destroy'

  get 'banners/index'

  get 'banners/show'

  get 'banners/new'

  get 'banners/create'

  get 'banners/edit'

  get 'banners/update'

  get 'banners/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/create'

  get 'users/new'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'purchases/index'

  get 'purchases/show'

  get 'purchases/new'

  get 'purchases/create'

  get 'purchases/edit'

  get 'purchases/update'

  get 'purchases/destroy'

  get 'complements/index'

  get 'complements/show'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/new'

  get 'complements/create'

  get 'complements/destroy'

  get 'raw_subcategories/index'

  get 'raw_subcategories/show'

  get 'raw_subcategories/new'

  get 'raw_subcategories/create'

  get 'raw_subcategories/edit'

  get 'raw_subcategories/update'

  get 'raw_subcategories/destroy'

  get 'raw_categories/index'

  get 'raw_categories/show'

  get 'raw_categories/new'

  get 'raw_categories/create'

  get 'raw_categories/edit'

  get 'raw_categories/update'

  get 'raw_categories/destroy'

  get 'raws/index'

  get 'raws/show'

  get 'raws/edit'

  get 'raws/update'

  get 'raws/new'

  get 'raws/create'

  get 'raws/destroy'

  get 'coupons/coupon_batch_actions' => "coupons#coupon_batch_actions", :as => 'coupon_batch_actions'

  get 'coupons/index'

  get 'coupons/show'

  get 'coupons/new'

  get 'coupons/create'

  get 'coupons/edit'

  get 'coupons/update'

  get 'coupons/destroy'

  get 'pictures/edit'

  get 'pictures/destroy'

  get 'colors/index'

  get 'colors/show'

  get 'colors/new'

  get 'colors/create'

  get 'colors/edit'

  get 'colors/update'

  get 'colors/destroy'

  get 'single_articles/index'

  get 'single_articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'categories/new'

  get 'categories/edit'

  get 'materials/index'

  get 'materials/show'

  get 'materials/new'

  get 'materials/edit'

  get 'articles/index'

  get 'articles/show'

  get 'articles/show_pics' => "articles#show_pics", :as => 'articles_gallery'

  get 'articles/new'

  get 'articles/create'

  get 'articles/edit'

  get 'articles/update'

  get 'articles/destroy'

  get 'articles/batch_actions' => "articles#batch_actions", :as => 'batch_actions'

  get 'articles/set_picture' => "articles#set_picture", :as => 'set_picture'

  get 'articles/import_view' => "articles#import_view", :as => 'import_view'

  get 'articles/edit_multiple' => "articles#edit_multiple", :as => 'edit_multiple'

  get 'articles/update_multiple' => "articles#update_multiple", :as => 'update_multiple'

  get 'articles/raw_index' => "articles#raw_index", :as => 'raw_index'

  get 'articles/raw_new' => "articles#raw_new", :as => 'raw_new'

  get 'articles/raw_show' => "articles#raw_show", :as => 'raw_show'

  get 'articles/set_auction' => "articles#set_auction", :as => 'set_auction'

  get 'articles/create_auction' => "articles#create_auction", :as => 'create_auction'

  get 'articles/index_auction' => "articles#index_auction", :as => 'index_auction'

  get 'complements/complement_set_picture' => "complements#complement_set_picture", :as => 'complement_set_picture'

  get 'dashboards/batch_options' => "dashboards#batch_options", :as => 'batch_options'

  root :to => 'dashboards#index'

  devise_for :admin_users, controllers: {sessions: "admin_users/sessions", registrations: "admin_users/registrations"}

  devise_scope :admin_user do
    get "login", to: "devise/sessions#new"
    authenticated :admin_user do
      root :to => 'dashboards#index', as: :authenticated_root
      get "sign_up", to: "devise/registrations#new"
    end
    unauthenticated :admin_user do
      root :to => 'admin_users/sessions#new', as: :unauthenticated_root
    end

    get "admin_users/sign_out" => redirect("devise/sessions#new")

    resources :home_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :shop_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :purchases
    resources :complements do
      put :complement_set_picture, on: :collection
    end
    resources :dashboards do
      put :batch_options, on: :collection
    end
    resources :categories
    resources :articles do
      get :index_auction, on: :collection
      put :create_auction, on: :collection
      put :set_auction, on: :collection
      get :raw_edit, on: :collection
      get :raw_new, on: :collection
      put :raw_show, on: :collection
      get :raw_index, on: :collection
      put :batch_actions, on: :collection
      put :set_discount, on: :collection
      put :set_picture, on: :collection
      post :import, on: :collection
      put :edit_multiple, on: :collection
      post :update_multiple, on: :collection
    end
    resources :materials
    resources :single_articles
    resources :colors
    resources :types
    resources :pictures
    resources :raw_categories
    resources :raw_subcategories
    resources :coupons do
      put :coupon_batch_actions, on: :collection
    end

  end

end

app/models/complement.rb
class Complement < ActiveRecord::Base
  has_many :article_complements
  has_many :single_articles, :through => :article_complements

  has_many :past_purchases
  has_many :users, :through => :past_purchases

  has_many :pictures, :dependent => :destroy

  belongs_to :picture
end

app/controllers/complements_controller.rb
class ComplementsController < ApplicationController

  def index
    @page_title = "Kompleti"
    @complements = Complement.all
    @complements_grid = initialize_grid(@complements, name: 'complements', include: [ :picture] ,order: 'complements.created_at', order_direction: 'desc', enable_export_to_csv: true, csv_file_name: 'kompleti', csv_field_separator: ';' )

    export_grid_if_requested
  end

  def show
    @complement = Complement.find(params[:id])
    @page_title = "Kompleti | " + (@complement.title)

    @discount_prize = nil

    if @complement.end_date != nil
      gon.date = @complement.end_date.strftime("%Y/%m/%d %H:%M")
    end

    if @complement.discount != nil && @complement.discount != 0
      @discount_prize = (@complement.cost-(@complement.cost*@complement.discount/100))
    end
  end

  def new
    @complement = Complement.new
    @page_title = "Kompleti | New"

    @codes = Article.select(:code).map(&:code)
  end

  def create
    @complement = Complement.new(complement_params)

    if @complement.save

      if params[:images]

        params[:images].each { |image|
          @complement.pictures.create(image: image)
        }
      end
    end

    if @complement.pictures != nil && @complement.pictures.first != nil
      @complement.picture = @complement.pictures.first
    end

    flash[:notice] = "Dodan je novi komplet!"

    redirect_to complements_index_path
  end

  def edit
    @complement = Complement.find(params[:format])
    @page_title = "Kompleti | " + @complement.title
  end

  def update
    @complement = Complement.find(params[:id])

    @complement.update(complement_params)

      if params[:images]

        params[:images].each { |image|
          @complement.pictures.create(image: image)
        }
      end

    flash[:notice] = "Komplet je izmijenjen!"

    redirect_to complements_index_path
  end

  def destroy
    @complement = Complement.find(params[:id])

    @complement.destroy

    flash[:notice] = "Komplet je izbrisan!"

    redirect_to complements_index_path
  end

  ###################################################################### batch actions
  def complement_batch_actions


  end

  ################################################## discount i auction

  def complement_discount
    @comp = Complement.where(id: params[:grid][:selected])
  end

  def complement_auction
    @comp = Complement.where(id: params[:grid][:selected])
  end

  ################################################################################

  def complement_set_picture # postavljanje avatar-a za artikl

    @pic = Picture.find(params[:format])

    if @pic.complement != nil
      @art = Complement.find(@pic.complement.id)
    end

    @art.picture = @pic

    @art.save

    redirect_to(:back)
  end


  protected
  def complement_params
    params.require(:complement).permit(:title, :title_eng, {single_article_ids:[] }, :description, :description_eng, :cost, :start_date, :end_date)
  end
end

app/helpers/complements_helper.rb
module ComplementsHelper
end

app/views/complements/_complements_grid.erb
<%= grid(@complements_grid, show_filters: :always) do |g|

  g.action_column do |t|
    t.id
  end

  g.column name: "", attribute: 'image_file_name', filter: false, assoc: :picture, in_csv: false do |t|
    if t.picture != nil
      image_tag t.picture.image.url(:table)
    else
      image_tag 'placeholder2.png'
    end
  end

  g.column name: "Naziv", attribute: 'title' do |t|
    link_to(t.title, complement_path(t.id), :method => :get)
  end

  g.column name: "Popust", attribute: 'discount', custom_filter: :auto do |t|
    t.discount? ? t.discount.to_s+"%" : "---"
  end

  g.column name: "Na Popustu", attribute: 'on_discount' do |t|
    t.on_discount? ? "Da" : "Ne"
  end

   g.column name: "Kreiran", attribute: 'created_at' do |t|
    t.created_at.strftime("%d. %m. %Y.")
  end

  g.column name: "Na prodaji", attribute: 'for_sale' do |t|
    t.for_sale? ? "Da" : "Ne"
  end

  g.column name: "Cijena(bez popusta)", attribute: 'cost' do |t|
    number_to_currency(t.cost, :unit => 'Kn', :format => "%n %u")
  end

  g.column name: "Cijena(sa popustom)", attribute: 'cost', filter: false do |t|
    if t.discount != nil && t.discount != 0
      number_to_currency((t.cost-(t.cost*t.discount/100)), :unit => 'Kn', :format => "%n %u")
    else
      "- - -"
    end
  end

  g.column in_csv: false do |t|
    link_to("Uredi", complements_edit_path(t.id), :method => :get)
  end

end-%>

app/views/complements/create.html.erb
<h1>Complements#create</h1>
<p>Find me in app/views/complements/create.html.erb</p>

app/views/complements/destroy.html.erb
<h1>Complements#destroy</h1>
<p>Find me in app/views/complements/destroy.html.erb</p>

app/views/complements/edit.html.erb
<h3>Novi Komplet</h3>


<%= simple_form_for @complement, html: {class: 'form-horizontal', multipart: true} do |f| %>
    <%= f.input :title, label: "Naziv" %>
    <%= f.input :title_eng, label:"Naziv na Engleskom" %>

    <%= f.label "Artikli" %>
    <%= f.association :single_articles, label: false, collection: SingleArticle.all, :include_blank => true, :input_html => {class: 'chosen-select', multiple: true} %>

    <%= f.input :description, label: "Opis" %>

    <%= f.input :description_eng, label: "Opis na Engleskom" %>

    <div class="control-group">
      <%= f.label :pictures, label: "Slike", :class => 'control-label' %>
      <div class="controls">

        <%= file_field_tag "images[]", type: :file, multiple: true %>
        <br/>
        <% @complement.pictures.each do |p| %>
            <div style="margin-top: 15px;">
              <%= link_to "Postavi kao Avatar", complement_set_picture_path(p.id), class: "btn btn-default"%>
              <%= link_to 'Delete',  picture_path(p.id),  method: :delete, data: { confirm: 'Jeste li sigurni?' },class: "btn btn-default" %>
              <%= image_tag p.image.url(:thumb) %>
            </div>
        <% end %>
        <p></p>
      </div>
    </div>

    <%= f.input :cost, label: "Cijena" %>

    <%= f.input :discount, label: "Popust(%)" %>

    <%= f.input :start_date, :as => :datetime , label: "Početak popusta" %>
    <%= f.input :end_date, :as => :datetime, label: "Kraj popusta" %>

    <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
      <span class="input-group-addon">
         <%= f.check_box :for_sale, label: "Postavi na prodaju", type: "checkbox" %>
      </span>
      <%= f.label "Postavi na prodaju", type: "text", class: "form-control" %>
    </div>

    <%= f.button :submit, "Uredi komplet", class: "btn btn-success" %>
    <%= link_to "Cancel", complements_path, class: "btn btn-default" %>

<% end %>

app/views/complements/index.html.erb
  <%= link_to "Novi Komplet", complements_new_path, class: "btn btn-success" %>


<%= link_to "Svi Artikli", articles_path, class: "btn btn-default pull-right RbtnMargin" %>
  <div class="page-header head-page">
  <h1>Kompleti</h1>
</div>


<%= form_tag batch_actions_path, :method => :put do |f| %>

    <div style="margin-bottom: 5px;" >

      <div class="dropdown" >
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="width: 105px;">
          Opcije
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">

          <li><a><%= submit_tag "Postavi popust", style: "background: white;" %></a></li>
          <li><a><%= submit_tag "Makni sa popusta", style: "background: white;" %></a></li>
          <li role="separator" class="divider"></li>
          <li><a><%= submit_tag "Stavi na Aukciju", style: "background: white;" %></a></li>
          <li role="separator" class="divider"></li>
          <li><a><%= submit_tag "Stavi na prodaju", style: "background: white;"  %></a></li>
          <li><a><%= submit_tag "Makni sa prodaje", style: "background: white;"  %></a></li>

        </ul>

        <%= submit_tag "Izbriši komplete",data: { confirm: 'Jeste li sigurni da želite obrisati odabrane komplete?' }, class: "btn btn-danger"%>
      </div>

    </div>

    <%= render partial: 'complements/complements_grid' %>

<% end %>

app/views/complements/new.html.erb
<h3>Novi Komplet</h3>


<%= simple_form_for @complement, html: {class: 'form-horizontal', multipart: true} do |f| %>
    <%= f.input :title, label: "Naziv" %>
    <%= f.input :title_eng, label:"Naziv na Engleskom" %>

    <%= f.label "Artikli" %>
    <%= f.association :single_articles, label: false, collection: SingleArticle.all, :include_blank => true, :input_html => {class: 'chosen-select', multiple: true} %>


    <%= f.input :description, label: "Opis" %>

    <%= f.input :description_eng, label: "Opis na Engleskom" %>

    <div class="control-group">
      <%= f.label :pictures, label: "Slike", :class => 'control-label' %>
      <div class="controls">

        <%= file_field_tag "images[]", type: :file, multiple: true %>

        <p></p>
      </div>
    </div>

    <%= f.input :cost, label: "Cijena" %>

    <%= f.input :discount, label: "Popust(%)" %>

    <%= f.input :start_date, :as => :datetime , label: "Početak popusta" %>
    <%= f.input :end_date, :as => :datetime, label: "Kraj popusta" %>

    <div class="input-group" style="margin-bottom: 10px; margin-top: 30px;">
      <span class="input-group-addon">
         <%= f.check_box :for_sale, label: "Postavi na prodaju", type: "checkbox" %>
      </span>
      <%= f.label "Postavi na prodaju", type: "text", class: "form-control" %>
    </div>

    <%= f.button :submit, "Izradi komplet", class: "btn btn-success" %>
    <%= link_to "Cancel", complements_path, class: "btn btn-default" %>

<% end %>

app/views/complements/show.html.erb
<%= javascript_tag do %>
    $(function(){

    ts = new Date(gon.date);

    if((new Date()) > ts){
    // The new year is here! Count towards something else.
    // Notice the *1000 at the end - time must be in milliseconds
    ts = new Date(gon.date);
    }

    $('#countdown').countdown({
    timestamp	: ts,
    callback	: function(days, hours, minutes, seconds){

    }
    });

    });
<% end %>

<%= link_to "Uredi Artikl", complements_edit_path(@complement.id), class: "btn btn-primary" %> <%= link_to 'Delete',  @complement,  method: :delete, data: { confirm: 'Jeste li sigurni?' },class: "btn btn-danger" %>  <%= link_to "Svi Artikli", complements_path, class: "btn btn-default pull-right" %>
<div class="page-header head-page">
  <h1><%= @complement.title %><% if !@complement.title_eng.blank? %> <small><%= @complement.title_eng %></small><% end %></h1>
</div>

<% if !@complement.for_sale? %>
    <div class="alert alert-danger" role="alert">
      <h4 style="margin-bottom: 0px;">Artikl nije stavljen na prodaju!</h4>
    </div>
<% end %>


<!--<div id="clock"></div>-->

<% if @complement.discount != nil && @complement.end_date != nil && @complement.end_date > DateTime.now && @complement.start_date <= DateTime.now %>
    <div id="countdown" class="countdownHolder" style="width: 100%; text-align: left">
    <span class="countDays">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

      <span class="countDiv countDiv0"></span>

    <span class="countHours">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

      <span class="countDiv countDiv1"></span>

    <span class="countMinutes">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

      <span class="countDiv countDiv2"></span>

    <span class="countSeconds">
      <span class="position">
        <span class="digit static"></span>
      </span>
      <span class="position">
        <span class="digit static"></span>
      </span>
    </span>

    </div>
<% end %>

<% if !@complement.picture.nil? %>
    <%= image_tag(@complement.picture.image.url(:gallery)) %>
<% else %>
    <%= image_tag('placeholder.png') %>
<% end %>
<br/>
<div class="panel panel-info" style="margin-top: 10px">
  <div class="panel-heading">
    <h3 class="panel-title">Info</h3>
  </div>
  <div class="panel-body">
    <div class="row" >
      <div class="col-xs-6 col-md-2" >
        <strong>Artikli:</strong> <% if @complement.single_articles != nil %> <% @complement.single_articles.each do |art| %>
                <p><%= link_to art.title, single_article_path(art.id) %></p>
            <% end %>
            <p><% else %> Nije postavljen ni jedan Artikl <% end %></p>
      </div>

      <div class="col-xs-6 col-md-2" >
        <strong>Cijena<% if @discount_prize %>(prije popusta) <% end %>:</strong> <p><%= number_to_currency(@complement.cost, :unit => 'Kn', :format => "%n %u") %></p>
      </div>

    </div>
    <br/>
    <div class="row">
      <% if @discount_prize != nil%>
          <div class="col-xs-6 col-md-2" >
            <strong>Cijena(poslije popusta):</strong> <p><%= number_to_currency(@discount_prize, :unit => 'Kn', :format => "%n %u") %></p>
          </div>

          <div class="col-xs-6 col-md-2" >
            <strong>Popust:</strong> <p><%= @complement.discount.to_s+"%" %></p>
          </div>

          <% if @complement.start_date != nil %>
              <div class="col-xs-6 col-md-2" >
                <strong>Pocetak-Kraj popusta:</strong> <p><%= @complement.start_date.strftime("%d.%m.%Y. %H:%M").to_s+" - "+@complement.end_date.strftime("%d.%m.%Y. %H:%M") %></p>
              </div>
          <% end %>
      <% end %>
    </div>



  </div>
</div>

<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Opis</h3>
  </div>
  <div class="panel-body">
    <div class="page-header head-page">
      <h5>HRV:</h5>
    </div>
    <% if !@complement.description.blank? %>
        <%= @complement.description %>
    <% else %>
        Nema opisa!
    <% end %>

    <div class="page-header">
      <h5>ENG:</h5>
    </div>
    <% if !@complement.description_eng.blank? %>
        <%= @complement.description_eng %>
    <% else %>
        No description!
    <% end %>
  </div>
</div>



<p><strong>Slike:</strong></p>

<div class="row" >

  <%= render_gallery_for @complement.pictures, list_tag: :div, item_tag: :p, item_class: "col-xs-6 col-md-3"  %>

</div>

app/views/complements/update.html.erb
<h1>Complements#update</h1>
<p>Find me in app/views/complements/update.html.erb</p>