config/routes.rb
Rails.application.routes.draw do

  get 'types/index'

  get 'types/show'

  get 'types/new'

  get 'types/create'

  get 'types/edit'

  get 'types/update'

  get 'types/destroy'

  get 'home_banners/index'

  get 'home_banners/show'

  get 'home_banners/new'

  get 'home_banners/create'

  get 'home_banners/edit'

  get 'home_banners/update'

  get 'home_banners/destroy'

  get 'shop_banners/index'

  get 'shop_banners/show'

  get 'shop_banners/new'

  get 'shop_banners/create'

  get 'shop_banners/edit'

  get 'shop_banners/update'

  get 'shop_banners/destroy'

  get 'banners/index'

  get 'banners/show'

  get 'banners/new'

  get 'banners/create'

  get 'banners/edit'

  get 'banners/update'

  get 'banners/destroy'

  get 'users/index'

  get 'users/show'

  get 'users/create'

  get 'users/new'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'purchases/index'

  get 'purchases/show'

  get 'purchases/new'

  get 'purchases/create'

  get 'purchases/edit'

  get 'purchases/update'

  get 'purchases/destroy'

  get 'complements/index'

  get 'complements/show'

  get 'complements/edit'

  get 'complements/update'

  get 'complements/new'

  get 'complements/create'

  get 'complements/destroy'

  get 'raw_subcategories/index'

  get 'raw_subcategories/show'

  get 'raw_subcategories/new'

  get 'raw_subcategories/create'

  get 'raw_subcategories/edit'

  get 'raw_subcategories/update'

  get 'raw_subcategories/destroy'

  get 'raw_categories/index'

  get 'raw_categories/show'

  get 'raw_categories/new'

  get 'raw_categories/create'

  get 'raw_categories/edit'

  get 'raw_categories/update'

  get 'raw_categories/destroy'

  get 'raws/index'

  get 'raws/show'

  get 'raws/edit'

  get 'raws/update'

  get 'raws/new'

  get 'raws/create'

  get 'raws/destroy'

  get 'coupons/coupon_batch_actions' => "coupons#coupon_batch_actions", :as => 'coupon_batch_actions'

  get 'coupons/index'

  get 'coupons/show'

  get 'coupons/new'

  get 'coupons/create'

  get 'coupons/edit'

  get 'coupons/update'

  get 'coupons/destroy'

  get 'pictures/edit'

  get 'pictures/destroy'

  get 'colors/index'

  get 'colors/show'

  get 'colors/new'

  get 'colors/create'

  get 'colors/edit'

  get 'colors/update'

  get 'colors/destroy'

  get 'single_articles/index'

  get 'single_articles/show'

  get 'categories/index'

  get 'categories/show'

  get 'categories/new'

  get 'categories/edit'

  get 'materials/index'

  get 'materials/show'

  get 'materials/new'

  get 'materials/edit'

  get 'articles/index'

  get 'articles/show'

  get 'articles/show_pics' => "articles#show_pics", :as => 'articles_gallery'

  get 'articles/new'

  get 'articles/create'

  get 'articles/edit'

  get 'articles/update'

  get 'articles/destroy'

  get 'articles/batch_actions' => "articles#batch_actions", :as => 'batch_actions'

  get 'articles/set_picture' => "articles#set_picture", :as => 'set_picture'

  get 'articles/import_view' => "articles#import_view", :as => 'import_view'

  get 'articles/edit_multiple' => "articles#edit_multiple", :as => 'edit_multiple'

  get 'articles/update_multiple' => "articles#update_multiple", :as => 'update_multiple'

  get 'articles/raw_index' => "articles#raw_index", :as => 'raw_index'

  get 'articles/raw_new' => "articles#raw_new", :as => 'raw_new'

  get 'articles/raw_show' => "articles#raw_show", :as => 'raw_show'

  get 'articles/set_auction' => "articles#set_auction", :as => 'set_auction'

  get 'articles/create_auction' => "articles#create_auction", :as => 'create_auction'

  get 'articles/index_auction' => "articles#index_auction", :as => 'index_auction'

  get 'complements/complement_set_picture' => "complements#complement_set_picture", :as => 'complement_set_picture'

  get 'dashboards/batch_options' => "dashboards#batch_options", :as => 'batch_options'

  root :to => 'dashboards#index'

  devise_for :admin_users, controllers: {sessions: "admin_users/sessions", registrations: "admin_users/registrations"}

  devise_scope :admin_user do
    get "login", to: "devise/sessions#new"
    authenticated :admin_user do
      root :to => 'dashboards#index', as: :authenticated_root
      get "sign_up", to: "devise/registrations#new"
    end
    unauthenticated :admin_user do
      root :to => 'admin_users/sessions#new', as: :unauthenticated_root
    end

    get "admin_users/sign_out" => redirect("devise/sessions#new")

    resources :home_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :shop_banners do
      put :banner_up, on: :collection
      put :banner_down, on: :collection
    end
    resources :purchases
    resources :complements do
      put :complement_set_picture, on: :collection
    end
    resources :dashboards do
      put :batch_options, on: :collection
    end
    resources :categories
    resources :articles do
      get :index_auction, on: :collection
      put :create_auction, on: :collection
      put :set_auction, on: :collection
      get :raw_edit, on: :collection
      get :raw_new, on: :collection
      put :raw_show, on: :collection
      get :raw_index, on: :collection
      put :batch_actions, on: :collection
      put :set_discount, on: :collection
      put :set_picture, on: :collection
      post :import, on: :collection
      put :edit_multiple, on: :collection
      post :update_multiple, on: :collection
    end
    resources :materials
    resources :single_articles
    resources :colors
    resources :types
    resources :pictures
    resources :raw_categories
    resources :raw_subcategories
    resources :coupons do
      put :coupon_batch_actions, on: :collection
    end

  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :category_subcategories
  has_many :subcategories, :through => :category_subcategories

  has_many :article_categories
  has_many :articles, :through => :article_categories

  has_many :category_materials
  has_many :materials, :through => :category_materials

  has_attached_file :avatar,
                    :styles => {thumb: "350x250#", table: "26x26#"}

  do_not_validate_attachment_file_type :avatar

  def self.options_for_select
    order('LOWER(title)').map { |e| [e.title, e.id] }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_admin_user!

  def index
    @page_title = "Kategorije"
    @categories = Category.all

    @subcategories = Subcategory.all
  end

  def show
    @category = Category.find(params[:id])
    @page_title = "Kategorije | " + @category.title
  end

  def new
    @category = Category.new
    @page_title = "Kategorije | New"
  end

  def create
    @category = Category.new(category_params)

    @category.save

    flash[:notice] = "Dodan je novi materijal!"

    redirect_to categories_index_path
  end

  def edit
    @category = Category.find(params[:format])
    @page_title = "Edit | "+@category.title
  end

  def update
    @category = Category.find(params[:id])

    @category.update(category_params)

    flash[:notice] = "Materijal je izmijenjen!"

    redirect_to categories_index_path
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy

    flash[:notice] = "Materijal je izbrisan!"

    redirect_to categories_index_path
  end

  protected
  def category_params
    params.require(:category).permit(:title,:title_eng,  material_ids:[])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h3>Uredi Kategoriju</h3>

<%= simple_form_for @category, html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :title, label: "Naziv" %>

    <%= f.input :title_eng, label: "Naziv na Engleskom" %>

    <%= f.input :avatar, label: "Slika" , as: :file %>

    <%= f.label "Materijali" %>
    <%= f.association :materials, label: false, collection: Material.all, multiple: true, :include_blank => true, :input_html => {class: 'chosen-select'} %>
    <%= f.button :submit, "Izmijeni kategoriju" %>
    <%= link_to "Cancel", category_path(f.object.id), class: "btn btn-default" %>

<% end %>

app/views/categories/index.html.erb
<%= link_to "Nova Kategorija", categories_new_path, class: "btn btn-success" %>
<div class="page-header head-page">
  <h1>Kategorije</h1>
</div>

<div class="list-group">
  <% @categories.each do |cat| %>
      <%= link_to cat.id.to_s+". "+cat.title, category_path(cat.id), class: 'list-group-item' %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h3>Nova Kategorija</h3>

<%= simple_form_for @category,  html: {class: 'form-horizontal'} do |f| %>
    <%= f.input :title, label: "Naziv" %>

    <%= f.input :title_eng, label: "Naziv na Engleskom" %>

    <%= f.input :avatar, label: "Slika" , as: :file %>

    <%= f.label "Materijali" %>
    <%= f.association :materials, label: false, collection: Material.all, multiple: true, :include_blank => true, :input_html => {class: 'chosen-select'} %>
    <%= f.button :submit, "Izradi kategoriju", class: "btn btn-success" %>
    <%= link_to "Cancel", categories_path, class: "btn btn-default" %>

<% end %>

app/views/categories/show.html.erb
<%= link_to "Uredi Kategoriju", categories_edit_path(@category.id), class: "btn btn-primary" %> <%= link_to 'Delete',  @category,  method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %> <%= link_to "Sve Kategorije", categories_path, class: "btn btn-default pull-right" %>
<div class="page-header head-page">
  <h1><%= @category.title %><% if @category.title_eng != nil %> <small><%= @category.title_eng %></small><% end %></h1>
</div>
<div style="margin-bottom: 15px;" >
  <% if !@category.avatar_file_name.nil? %>
      <%= image_tag(@category.avatar.url(:thumb)) %>
  <% else %>
      <%= image_tag('placeholder.png') %>
  <% end %>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Materijali</h3>
  </div>
  <ul class="list-group">
    <% @category.materials.each do |mat| %>
          <%= link_to mat.id.to_s+". "+mat.title, material_path(mat.id), class:"list-group-item" %>
    <% end %>
  </ul>

</div>



<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Artikli</h3>
  </div>
  <ul class="list-group">
    <% @category.articles.each do |art| %>
          <%= link_to art.title, article_path(art.id), method: :get ,class:"list-group-item"  %>
    <% end %>
  </ul>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>